language: node_js
node_js:
  - "6"
  - "8"
  - "10"
script:
  - npm install -g codecov nyc
  - yarn build
  - TZ=America/Vancouver yarn test
  - TZ=America/Los_Angeles yarn test
  - TZ=Africa/Nairobi yarn test
  - TZ=Asia/Tokyo yarn test-ci
after_success:
  - nyc report --reporter=json && codecov -f coverage/*.json
sudo: false
